# Generated by Django 5.1 on 2026-06-11 06:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passport', '0005_add_verification_badges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('paper', 'Công trình khoa học'), ('patent', 'Bằng sáng chế'), ('invention', 'Giải pháp hữu ích'), ('research', 'Kết quả nghiên cứu'), ('dataset', 'Bộ dữ liệu'), ('software', 'Phần mềm'), ('other', 'Khác')], max_length=20)),
                ('source_id', models.CharField(blank=True, default='', help_text='ID of the Paper/Patent/ResearchResult this was minted from', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('abstract', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='marketplace/thumbnails/')),
                ('documents', models.JSONField(blank=True, default=list, help_text='List of document URLs/paths attached to this IP')),
                ('token_id', models.CharField(blank=True, help_text='On-chain token ID (populated after mint)', max_length=100, null=True, unique=True)),
                ('token_standard', models.CharField(default='ERC-721', help_text='ERC-721 for unique IP, ERC-1155 for fractionalized', max_length=20)),
                ('token_uri', models.URLField(blank=True, default='')),
                ('contract_address', models.CharField(blank=True, default='', max_length=100)),
                ('chain_id', models.IntegerField(default=1, help_text='Blockchain network ID')),
                ('tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('is_fractionalized', models.BooleanField(default=False)),
                ('total_fractions', models.IntegerField(default=1)),
                ('available_fractions', models.IntegerField(default=1)),
                ('fraction_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per fraction in VND', max_digits=18)),
                ('royalty_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Creator royalty % on secondary sales', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('zkp_proof_hash', models.CharField(blank=True, default='', help_text='ZK proof hash for confidential IP verification', max_length=128)),
                ('is_confidential', models.BooleanField(default=False, help_text='If True, full details hidden until purchase/license')),
                ('vkac_credential_id', models.CharField(blank=True, default='', help_text='VKAC DLT credential reference', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_assets', to='passport.expertprofile')),
            ],
            options={
                'verbose_name': 'IP Asset',
                'verbose_name_plural': 'IP Assets',
                'db_table': 'marketplace_ip_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Asking price in VND', max_digits=18)),
                ('min_bid', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum bid for auction-style listings', max_digits=18, null=True)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('license_type', models.CharField(choices=[('exclusive', 'Độc quyền'), ('non_exclusive', 'Không độc quyền'), ('transfer', 'Chuyển nhượng hoàn toàn'), ('research_only', 'Chỉ nghiên cứu'), ('commercial', 'Thương mại')], default='non_exclusive', max_length=20)),
                ('license_terms', models.TextField(blank=True, default='', help_text='Detailed licensing terms and conditions')),
                ('license_duration_months', models.IntegerField(blank=True, help_text='License duration in months (null = perpetual)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Đang niêm yết'), ('in_escrow', 'Đang ký quỹ'), ('sold', 'Đã bán'), ('licensed', 'Đã cấp phép'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.ipasset')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'marketplace_listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('message', models.TextField(blank=True, default='')),
                ('accepted', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.listing')),
            ],
            options={
                'db_table': 'marketplace_bid',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('royalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('escrow_funded', 'Đã ký quỹ'), ('delivered', 'Đã chuyển giao'), ('completed', 'Hoàn thành'), ('disputed', 'Tranh chấp'), ('refunded', 'Hoàn tiền'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('escrow_contract', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_sales', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'marketplace_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
