# Generated by Django 5.1 on 2026-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('expert', 'Expert'), ('business', 'Business'), ('organization', 'Organization'), ('admin', 'Admin'), ('manager', 'Manager'), ('verification_staff', 'Verification Staff')], default='expert', max_length=20),
        ),
    ]
