# Generated by Django 5.1 on 2026-06-04 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connect', '0001_initial'),
        ('passport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.TextField(blank=True, help_text='768-dim vector (pgvector)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Cached fields for filtering')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'expert_vectors',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.FloatField(help_text='Overall match score 0-100')),
                ('semantic_score', models.FloatField(default=0, help_text='Semantic similarity component')),
                ('field_overlap_score', models.FloatField(default=0, help_text='Field overlap component')),
                ('verified_bonus', models.FloatField(default=0, help_text='Verified credentials bonus')),
                ('explanation', models.TextField(blank=True, help_text='Human-readable explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='passport.expertprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='connect.expertiserequest')),
            ],
            options={
                'db_table': 'match_results',
                'ordering': ['-total_score'],
                'unique_together': {('request', 'expert')},
            },
        ),
    ]
