# Generated by Django 5.1 on 2026-06-04 05:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('orcid', models.CharField(blank=True, default='', max_length=50)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('degree', models.CharField(blank=True, default='', max_length=100)),
                ('fields', models.JSONField(blank=True, default=list, help_text='List of expertise fields')),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='expert_avatars/')),
                ('did_uri', models.CharField(blank=True, default='', max_length=255)),
                ('profile_completeness', models.IntegerField(default=0, help_text='Percentage of profile completion', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_public', models.BooleanField(default=True)),
                ('privacy_settings', models.JSONField(blank=True, default=dict, help_text='Granular privacy settings for profile fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expert_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('other', 'Other')], default='pdf', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Data extracted from document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(help_text='e.g. degree, certification, award', max_length=100)),
                ('subject_field', models.CharField(blank=True, default='', max_length=255)),
                ('vc_jwt', models.TextField(blank=True, default='', help_text='JWT-encoded Verifiable Credential')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issuer_did', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'credentials',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('journal', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, default='', max_length=255)),
                ('co_authors', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='manual', help_text='Source: orcid, crossref, manual, pdf', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='passport.expertprofile')),
                ('vc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='passport.credential')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
