# Generated by Django 5.1 on 2026-06-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='google_scholar',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='hide_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='hourly_rate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='id_card_verify_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='identification_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='main_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='fields',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise fields (nganh/specialization)'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='publication',
            name='source',
            field=models.CharField(blank=True, default='manual', max_length=50),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('earn_date', models.DateField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'awards',
                'ordering': ['-earn_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'educations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('link', models.URLField(blank=True)),
                ('cited_by', models.CharField(blank=True, max_length=50)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'papers',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=100)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('earn_date', models.DateField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'patents',
                'ordering': ['-earn_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'professional_associations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('sponsor', models.CharField(blank=True, max_length=255)),
                ('result', models.TextField(blank=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('result', models.TextField(blank=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_results', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'research_results',
            },
        ),
        migrations.CreateModel(
            name='ScienceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='science_activities', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'science_activities',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='passport.expertprofile')),
            ],
            options={
                'db_table': 'work_experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
