# Generated by Django 5.1 on 2026-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_expertprofile_address_expertprofile_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='google_scholar',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='website',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
