# Generated by Django 5.1 on 2026-06-10 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0004_expertprofile_researchgate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='identity_verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='identity_verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='identity_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='professional_verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='professional_verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='professional_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='professional_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='professional_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
